name: Build and Deploy

on:
  push:

jobs:
  checkout-demo:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout repo
        uses: actions/checkout@v3

      - name:  Step 2
        run: echo "Step 2 running"

      - name:  List files
        run: ls -la
