name: Build and Deploy

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name:  Step 1
        run: echo "Step 1 running"

      - name:  Step 2
        run: echo "Step 2 running"

      - name:  Step 3
        run: echo "Step 3 running"

      - name: Break it
        run: exit 1
