name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  checkout-demo:
    runs-on: ubuntu-latest
    env:
      MY_NAME: Tanner

    steps:
      - name: Print variable
        run: echo "Hello $MY_NAME"

      - name:  Checkout repo
        uses: actions/checkout@v3

      - name:  List files
        run: ls -la

  job2:
    needs: checkout-demo
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 2 running"
